#!/bin/bash

#coarse and filter mics for gempicker to 20-40A, do the same with references
#for i in `ls aligned_sums/*.mrc | sed 's/aligned_sums//g'`;do e2proc2d.py aligned_sums${i} aligned_sums_c4_f30${i} --meanshrink 4 --process=filter.lowpass.gauss:apix=5.64:cutoff_abs=0.376 --process=normalize.edgemean ;done

#------------------------INPUT PARAMETERS---------------------------
prog="/usr/local/gempicker/bin/gEMpicker"
micrographs="$PWD/img"  # only mrc files
refs="$PWD/tpl"         # only mrc files
msk="$PWD/msk"          # only tif files
output="$PWD/output"
threshold_low="0.1"
threshold_high="0.3"
box="80"              #desired box size, px
angle="10"            # angular step of template search, degrees
contrast="1"          # 1 - both mics and references have the same contrast, otherwise - 0
maxpeaks="50"         # max number of particles per micrograph
dist="60"             # minimal distance between picked particles, px
#-------------------------------------------------------------------
[ ! -d $res ] && mkdir $res
( [ ! -d $orig ] || [ ! -d $tpl ] || [ ! -d $msk ] ) && ( echo "Some directories was not found!" && exit 1 )
D1=`date +%s`
echo -e "Started on `date`"
for m in `seq 0 1`
do
${prog} --nGPU=1 --nCPU=8 --mode=$m --thresh=${threshold_low} --threshHigh=${threshold_high} --dirSch=${refs} --dirTgt=${micrographs} --dirMskSch=${msk} --dirRes=${output} --angle2D=${angle} --contrast=${contrast} --boxSize=${box} --nPickMax=${maxpeaks} --boxDist=${dist}
done
D2=`date +%s` ; D=$((D2-D1)) ; printf "Job duration = %dhr %dmin %dsec \n" $(($D/3600)) $(($D/60%60)) $(($D%60))
#----------------COMMENTS-------------------------------------------
<<comments
a) Supported mrc file formats: int8, int16, uint16, float32
b) Max size of micrographs is 4096x4096px.
c) Number of masks should be either one (for all references) or equal to the number of references.
d) The coordinates of picked particles are exported in the folder $Res/pik_coord.
e) The range of correlation values is overlaid on the correlation map exported in TIFF format. TIFF files are in uint8 for visualization purpose only.

 USAGE: 
   /usr/local/gempicker/bin/gEMpicker  --dirTgt=<string> --dirSch=<string>
                                       [--dirMskRef=<string>]
                                       --dirMskSch=<string>
                                       --dirRes=<string> --mode=<unsigned
                                       int> --angle2D=<float>
                                       --contrast=<bool> --thresh=<float>
                                       [--threshHigh=<float>]
                                       [--nPickMax=<unsigned int>]
                                       [--boxSize=<unsigned int>]
                                       [--boxDist=<unsigned int>]
                                       [--nCPU=<unsigned int>]                                                                                                                                                                               
                                       [--nGPU=<unsigned int>]                                                                                                                                                                               
                                       [--mpiDistTgt=<bool>] [--]                                                                                                                                                                            
                                       [--version] [-h]                                                                                                                                                                                      
                                                                                                                                                                                                                                            
Where:                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
   --dirTgt=<string>                                                                                                                                                                                                                         
     (required)  Directory of target micrograph images (*.mrc)                                                                                                                                                                               
                                                                                                                                                                                                                                             
   --dirSch=<string>                                                                                                                                                                                                                         
     (required)  Directory of search reference images (*.mrc)                                                                                                                                                                                
                                                                                                                                                                                                                                             
   --dirMskRef=<string>                                                                                                                                                                                                                      
     Directory of masks for target images (*.tif)                                                                                                                                                                                            
                                                                                                                                                                                                                                             
   --dirMskSch=<string>                                                                                                                                                                                                                      
     (required)  Directory of masks for search images (*.tif)                                                                                                                                                                                
                                                                                                                                                                                                                                             
   --dirRes=<string>                                                                                                                                                                                                                         
     (required)  Directory for results                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
   --mode=<unsigned int>                                                                                                                                                                                                                     
     (required)  Running mode: 0-compute correlation, 1-perform picking                                                                                                                                                                      
     (box only), 2-perform picking

   --angle2D=<float>
     (required)  In-plane rotating angle in degree, (0 = no rotation)

   --contrast=<bool>
     (required)  Micrograph contrast: 0-negative peaks, 1-positive peaks

   --thresh=<float>
     (required)  Threshold value for picking - low limit: (0,1]

   --threshHigh=<float>
     Threshold value for picking - high limit: (0,1]

   --nPickMax=<unsigned int>
     Max number of particles picked from each micrograph (0 = no limit)

   --boxSize=<unsigned int>
     Size of picked images (if not provided or = 0, use search image size)

   --boxDist=<unsigned int>
     Minimal distance between peaks (if not provided or = 0, use search
     image half-size)

   --nCPU=<unsigned int>
     Number of CPU cores / process

   --nGPU=<unsigned int>
     Number of GPUs / process

   --mpiDistTgt=<bool>
     Distribution of target images to processes: 0-no, 1-yes

   --,  --ignore_rest
     Ignores the rest of the labeled arguments following this flag.

   --version
     Displays version information and exits.

   -h,  --help
     Displays usage information and exits.


   gEMpicker is a template-based, highly parallel GPU-accelerated particle
   picking program developed at INRIA Nancy. It runs in multi-thread and
   multi-process mode to use all avaliable CPU cores and GPUs in a single
   workstation or a multi-node cluster for the correlation computation. 

   Supported formats: MRC for target and search images, TIFF for masks 

   Copyright: Thai V. Hoang, INRIA 

   Email: vanthai.hoang@inria.fr 

   Reference: 

   T. V. Hoang, X. Cavin, P. Schultz, and D. W. Ritchie, "gEMpicker: A
   highly parallel GPU-accelerated tool for electron micrograph particle
   picking," BMC Structural Biology, 2013.
comments
