#!/bin/bash
export IMAGIC_BATCH=1
IMAGIC_ROOT="/home/imagic/imagic_110308_64"
echo "This script produces mount images from spotscan tif images and also perform block convolution"
echo "Enter pixel size: "
read pix
echo "Number of images along X-axis (vertical in IMAGIC) was: "
read Xim
echo "Number of images along Y-axis (horizontal in IMAGIC) was: "
read Yim
echo "Choose linear size of convolution area (3,5,7...)?"
read conv
if [ $((conv % 2 )) -ne 0 -a "${conv}" -gt 3 ]
then
total=$((Xim*Yim))
tifnum=`ls *.tif | wc -l`
serienum=$((${tifnum}/${total}))
for ((a=1; a <= serienum ; a++))
do

echo "! "
echo "! IMAGIC program: em2em ------------------------------------------------"
echo "! "
${IMAGIC_ROOT}/stand/em2em.e <<EOF
TIFF
IMAGIC
NO
YES
INTERACTIVE
serie${a}#
1,${total}
0
tif
serie${a}raw
${pix}
${a}
EOF
echo "! "
echo "! IMAGIC program: incnorvar --------------------------------------------"
echo "! "
${IMAGIC_ROOT}/incore/incnorvar.e <<EOF
WHOLE
serie${a}raw
serie${a}
1
EOF
rm "serie${a}raw.*";
echo "! "
echo "! IMAGIC program: mount ------------------------------------------------"
echo "! "
${IMAGIC_ROOT}/stand/mount.e <<EOF
serie${a}
mount${a}
2D
${Xim},${Yim}
0,0
EOF
echo "! "
echo "! IMAGIC program: block2d ----------------------------------------------"
echo "! "
${IMAGIC_ROOT}/block/block2d.e <<EOF
mount${a}
block${a}
LOW
${conv}
EOF
echo "! "
echo "! IMAGIC program: em2em ------------------------------------------------"
echo "! "
${IMAGIC_ROOT}/stand/em2em.e <<EOF
IMAGIC
MRC
SIN
2D
block${a}
block${a}
0
mrc
YES
EOF
echo "! "
echo "! IMAGIC program: em2em ------------------------------------------------"
echo "! "
${IMAGIC_ROOT}/stand/em2em.e <<EOF
IMAGIC
MRC
SIN
2D
mount${a}
mount${a}
0
mrc
YES
EOF
done
else
echo "Wrong number! Exiting"
fi
